# Generated by Django 4.2.5 on 2024-01-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualExpert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affliate_marketing',
            name='created_date',
        ),
    ]
