# Generated by Django 4.1 on 2023-12-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualExpert', '0003_ad_distributor_otp1_ad_distributor_user_otp1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_distributor',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ad_provider',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
