# Generated by Django 4.2.5 on 2024-01-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualExpert', '0003_affliate_marketing_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_client',
            name='active_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
