# Generated by Django 4.2.5 on 2024-01-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualExpert', '0004_ad_client_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='aid',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='my_client',
            field=models.TextField(null=True),
        ),
    ]
