# Generated by Django 4.1 on 2023-12-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualExpert', '0004_alter_ad_distributor_otp_alter_ad_provider_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringmanager',
            name='otp1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hiringmanager',
            name='user_otp1',
            field=models.IntegerField(null=True),
        ),
    ]
