# Generated by Django 4.1 on 2023-12-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualExpert', '0005_hiringmanager_otp1_hiringmanager_user_otp1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_distributor',
            name='sales_manager',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ad_provider',
            name='sales_manager',
            field=models.TextField(null=True),
        ),
    ]
