# Generated by Django 4.2.5 on 2024-01-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualExpert', '0005_users_aid_users_my_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='mobile',
        ),
    ]
