# Generated by Django 4.1 on 2023-12-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualExpert', '0006_ad_distributor_sales_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanager',
            name='ad_distributor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='salesmanager',
            name='ad_provider',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='salesmanager',
            name='my_profile_manager',
            field=models.TextField(null=True),
        ),
    ]
