# Generated by Django 5.0 on 2024-01-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualExpert', '0006_remove_users_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
