# Generated by Django 5.0 on 2024-02-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualExpert', '0009_ad_distributor_arn_no_ad_distributor_company_pan_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_distributor',
            name='verification_img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ad_provider',
            name='verification_img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='affliate_marketing',
            name='verification_img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hiringmanager',
            name='verification_img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profilemanager',
            name='verification_img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='salesmanager',
            name='verification_img',
            field=models.TextField(null=True),
        ),
    ]
