# Generated by Django 4.1 on 2024-03-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualExpert', '0010_ad_distributor_verification_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiringmanager',
            old_name='personal_address',
            new_name='house_number',
        ),
        migrations.AddField(
            model_name='hiringmanager',
            name='personal_age',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hiringmanager',
            name='personal_dob',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hiringmanager',
            name='pin_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hiringmanager',
            name='street_name',
            field=models.TextField(null=True),
        ),
    ]
