# Generated by Django 4.2.5 on 2024-01-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefinder',
            name='otp1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profilefinder',
            name='user_otp1',
            field=models.IntegerField(null=True),
        ),
    ]
