# Generated by Django 4.2.3 on 2023-08-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_profilefinder_profileforwho'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefinder',
            name='gender',
            field=models.TextField(null=True),
        ),
    ]
