# Generated by Django 4.2.5 on 2024-01-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_profilefinder_otp1_profilefinder_user_otp1'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_investigator',
            name='otp1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='user_otp1',
            field=models.IntegerField(null=True),
        ),
    ]
