# Generated by Django 4.2.5 on 2024-01-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_private_investigator_otp1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsViewedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PF_id', models.TextField(null=True)),
                ('Ads_id', models.TextField(null=True)),
                ('no_views', models.TextField(null=True)),
            ],
        ),
    ]
