# Generated by Django 4.2.3 on 2023-08-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_profilefinder_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='requested_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_phone_number', models.TextField(null=True)),
                ('request_whatsapp_number', models.TextField(null=True)),
                ('request_address', models.TextField(null=True)),
                ('request_horoscope', models.TextField(null=True)),
                ('request_social_media_link', models.TextField(null=True)),
            ],
        ),
    ]
