# Generated by Django 4.2.5 on 2024-01-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_adsvieweduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilefinder_adshilights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(null=True)),
                ('ads_languages', models.TextField(null=True)),
                ('ads_country', models.TextField(null=True)),
                ('ads_state', models.TextField(null=True)),
                ('ads_district', models.TextField(null=True)),
                ('ads_gender', models.TextField(null=True)),
                ('age_range', models.IntegerField(null=True)),
                ('age_to', models.IntegerField(null=True)),
                ('id_card', models.TextField(null=True)),
                ('Total_views', models.TextField(null=True)),
                ('ads_days_required', models.TextField(null=True)),
                ('ads_times_repeat', models.TextField(null=True)),
            ],
        ),
    ]
