# Generated by Django 4.2.3 on 2023-08-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_requested_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested_list',
            name='uid',
            field=models.TextField(null=True),
        ),
    ]
