# Generated by Django 4.2.5 on 2024-01-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_profilefinder_adshilights'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profilefinder_adshilights',
            new_name='profilefinder_ads_hilights',
        ),
    ]
