# Generated by Django 4.2.3 on 2023-08-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_requested_list_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested_list',
            name='requested_uid',
            field=models.TextField(null=True),
        ),
    ]
