# Generated by Django 4.2.5 on 2024-01-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_rename_profilefinder_adshilights_profilefinder_ads_hilights'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profilefinder_ads_hilights',
            new_name='profilefinder_ads_highlights',
        ),
    ]
