# Generated by Django 4.2.5 on 2024-01-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_rename_profilefinder_ads_hilights_profilefinder_ads_highlights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefinder_ads_highlights',
            name='id_card',
        ),
    ]
