# Generated by Django 4.2.3 on 2023-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_requested_list_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='received_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(null=True)),
                ('requested_uid', models.TextField(null=True)),
                ('request_phone_number', models.TextField(null=True)),
                ('request_whatsapp_number', models.TextField(null=True)),
                ('request_address', models.TextField(null=True)),
                ('request_horoscope', models.TextField(null=True)),
                ('request_social_media_link', models.TextField(null=True)),
                ('action', models.TextField(null=True)),
            ],
        ),
    ]
