# Generated by Django 4.2.3 on 2023-08-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_received_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='received_list',
            old_name='requested_uid',
            new_name='received_uid',
        ),
        migrations.RenameField(
            model_name='received_list',
            old_name='uid',
            new_name='sender_uid',
        ),
        migrations.RenameField(
            model_name='requested_list',
            old_name='requested_uid',
            new_name='received_uid',
        ),
        migrations.RenameField(
            model_name='requested_list',
            old_name='uid',
            new_name='sender_uid',
        ),
    ]
