# Generated by Django 4.2.5 on 2024-01-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_remove_profilefinder_ads_highlights_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefinder_ads_highlights',
            name='pf_data',
            field=models.TextField(null=True),
        ),
    ]
