# Generated by Django 4.2.3 on 2023-08-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_rename_requested_uid_received_list_received_uid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requested_list',
            new_name='sender_list',
        ),
    ]
