# Generated by Django 4.2.3 on 2023-08-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_rename_requested_list_sender_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_blocked_id', models.TextField(null=True)),
                ('blocked_id', models.TextField(null=True)),
                ('reason', models.TextField(null=True)),
            ],
        ),
    ]
