# Generated by Django 4.2.5 on 2024-01-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_profilefinder_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefinder',
            name='created_time',
            field=models.TextField(null=True),
        ),
    ]
