# Generated by Django 5.0 on 2024-02-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0011_profilefinder_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_investigator',
            name='arn_no',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='company_pan_no',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='degree_cer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='ex_cer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='ex_company_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='ex_job_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='ex_location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='field_study',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='gst_certificate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='gst_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='level_education',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='pan_card',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='work_company_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='work_job_location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='work_job_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='work_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='private_investigator',
            name='year_experience',
            field=models.TextField(null=True),
        ),
    ]
