# Generated by Django 4.2.3 on 2023-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0011_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='who_blocked_me',
            field=models.TextField(null=True),
        ),
    ]
