# Generated by Django 5.0 on 2024-02-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_private_investigator_arn_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_investigator',
            name='verification_img',
            field=models.TextField(null=True),
        ),
    ]
