# Generated by Django 4.2.3 on 2023-09-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0013_profilefinder_registered_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfavorite_id', models.TextField(null=True)),
                ('who_favorite_me_id', models.TextField(null=True)),
            ],
        ),
    ]
