# Generated by Django 4.1 on 2024-03-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0013_private_investigator_verification_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_investigator',
            name='notification_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
