# Generated by Django 4.2.3 on 2023-09-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='my_id',
            field=models.TextField(null=True),
        ),
    ]
