# Generated by Django 4.2.5 on 2023-09-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0017_saved_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_search',
            name='my_id',
            field=models.TextField(null=True),
        ),
    ]
