# Generated by Django 4.2.5 on 2023-09-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0018_saved_search_my_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_search',
            name='filterd_data',
            field=models.TextField(null=True),
        ),
    ]
