# Generated by Django 4.2.5 on 2023-09-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0019_saved_search_filterd_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_search',
            name='filterd_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.profilefinder'),
        ),
    ]
