# Generated by Django 4.2.5 on 2023-09-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0020_alter_saved_search_filterd_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_search',
            name='filterd_data',
            field=models.TextField(null=True),
        ),
    ]
