# Generated by Django 4.2.5 on 2023-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0021_alter_saved_search_filterd_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='private_investigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.TextField()),
                ('password', models.TextField()),
                ('otp', models.IntegerField()),
                ('user_otp', models.IntegerField(null=True)),
                ('profile_picture', models.TextField(null=True)),
            ],
        ),
    ]
