# Generated by Django 4.2.5 on 2023-10-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0024_private_investigator_my_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefinder',
            name='my_investigator',
            field=models.TextField(null=True),
        ),
    ]
