# Generated by Django 4.2.5 on 2023-10-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0026_alter_private_investigator_my_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private_investigator',
            name='my_client',
        ),
    ]
