# Generated by Django 4.2.5 on 2023-10-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0028_private_investigator_my_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_investigator',
            name='my_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.profilefinder'),
        ),
    ]
