# Generated by Django 4.2.5 on 2023-10-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0029_alter_private_investigator_my_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_investigator',
            name='my_client',
            field=models.TextField(null=True),
        ),
    ]
