# Generated by Django 4.2.6 on 2023-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0031_profilefinder_questin_and_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefinder',
            old_name='Questin_and_answer',
            new_name='Questin',
        ),
        migrations.AddField(
            model_name='profilefinder',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
