# Generated by Django 4.2.6 on 2023-10-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0032_rename_questin_and_answer_profilefinder_questin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_investigator',
            name='total_ratings',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profilefinder',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profilefinder',
            name='rating',
            field=models.TextField(null=True),
        ),
    ]
