# Generated by Django 4.2.6 on 2023-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0033_private_investigator_total_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_investigator',
            name='all_ratings',
            field=models.TextField(null=True),
        ),
    ]
