# Generated by Django 4.2.6 on 2023-11-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0035_alter_private_investigator_total_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_investigator',
            name='total_ratings',
            field=models.TextField(null=True),
        ),
    ]
