# Generated by Django 4.2.7 on 2023-12-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0039_profilefinder_my_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefinder',
            name='complaints',
            field=models.TextField(null=True),
        ),
    ]
