# Generated by Django 4.2.7 on 2023-12-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0040_profilefinder_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefinder',
            name='complaints_replay',
            field=models.TextField(null=True),
        ),
    ]
