# Generated by Django 4.2.7 on 2023-12-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0041_profilefinder_complaints_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefinder',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
