# Generated by Django 4.2.7 on 2023-12-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0042_profilefinder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefinder',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
