# Generated by Django 4.2.7 on 2023-12-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0043_profilefinder_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_investigator',
            name='sign_document',
            field=models.TextField(null=True),
        ),
    ]
