# Generated by Django 4.2.5 on 2024-01-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emra_coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField()),
                ('currency', models.TextField()),
                ('emra_coin_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='external_expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('to', models.TextField()),
                ('date', models.TextField()),
                ('currency', models.TextField()),
                ('amount', models.TextField()),
                ('frequency', models.TextField()),
                ('attachment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subscription_Country', models.TextField()),
                ('Title_of_the_plan', models.TextField()),
                ('Type_Of_Subscription', models.TextField()),
                ('Amount_with_ad', models.IntegerField()),
                ('Amount_without_ad', models.IntegerField()),
                ('Validity', models.TextField()),
                ('Option1', models.TextField()),
                ('Option2', models.TextField()),
                ('Option3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='superadmin_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
    ]
