# Generated by Django 5.0 on 2024-01-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('commision_start', models.DateField(null=True)),
                ('commision_end', models.DateField(null=True)),
                ('to_whom', models.TextField(null=True)),
                ('from_whom', models.TextField(null=True)),
                ('for_what', models.TextField(null=True)),
                ('how_many', models.TextField(null=True)),
                ('subscription', models.TextField(null=True)),
                ('commision', models.TextField(null=True)),
                ('how_many_coin', models.TextField(null=True)),
                ('how_many_views', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='insentives_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_target', models.TextField(null=True)),
                ('Incentives_Amount_INR', models.TextField(null=True)),
                ('Incentives_Amount_USD', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='third_party_user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_no', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('access_privilage', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='value1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='value2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='value3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Amount_with_ad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Amount_without_ad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Option1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Option2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Option3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Validity',
            field=models.TextField(null=True),
        ),
    ]
