# Generated by Django 5.0 on 2024-01-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_commision_insentives_settings_third_party_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pi_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_amount', models.TextField(null=True)),
                ('to_Admin', models.TextField(null=True)),
                ('to_investigator', models.TextField(null=True)),
            ],
        ),
    ]
