# Generated by Django 5.0 on 2024-01-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_pi_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='pi_performance_calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calculation_Period', models.TextField(null=True)),
                ('default_amount', models.TextField(null=True)),
                ('fifty_Good_Review', models.TextField(null=True)),
                ('eighty_Good_Review', models.TextField(null=True)),
                ('fifty_bad_Review', models.TextField(null=True)),
                ('eighty_bad_Review', models.TextField(null=True)),
            ],
        ),
    ]
